version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      # - test-3.8
      - test-pypy3.6

jobs:
  test-3.6: &test-template
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install .
      - run:
          name: Run tests
          command: |
            pytest
  test-3.7:
    <<: *test-template
    docker:
      - image: python:3.7
  test-3.8:
    <<: *test-template
    docker:
        - image: python:3.8.0a4
  test-pypy3.6:
    <<: *test-template
    docker:
        - image: pypy:3.6
